:toc: right

= Clean Code in Practice

:source-highlighter: coderay


== Introduction 

Do you use Clean Code practices on a daily basis. If yes, why? If no, why?

This post, follows the https://www.interventure.info/[InterVenture] Jam Session talk, "Clean Code in Practice". The talk is targeting an interesting phenomena.

IMPORTANT: Majority of developers are familiar and appreciative about the Clean Code practices. However, in practice they use only a handful of routines.

This is a personal observation that I keep asserting as true. Let me give you an example.
During the talk, amongst the thirty something developers of varying experience,
all have said that they have heard about Clean Code.
When followed with a question of who's using the routines on a daily basis.
There was only a single hand still standing.

What is behind this mismatch? Is it that we don't believe in the benefits of Clean Code?
Or is it that the costs are not worth the benefit?

Clean Code in practice talk tries to asses the value of Clean Code when applied
to real life applications.

We target a well known Spring PetClinic app as an example of a source code that is on pair to with the code we do on our everyday basis.
We'll review it from the Clean Code perspective and asses the value of
the changes brought upon the applied Clean Code practices.

This series of blog posts presents the findings.

=== Cycling Helmet Analogy

Why don't we use CC routines more often? I can express my belief with an analogy. Do you use a cycling helmet when going for a joy ride? Despite being an undisputable good thing, many don't. The belief that you won't really need it, combined with a slight nuisance of having to carry it around, topped with a potentially ruined hair style, makes the decision of ignoring the helmet quite likely. Even if it can be a life saver.

It's not that we're not aware of the risk. I rarely see kids without the helmet. However, we ourselves, we feel as pro's.
 We ride for a long time, and believe competent enough that we will not fall. It will not happen to us, not to us or not this time.

Until we do fall. Afterwards, the helmet is a must, and we frown upon people ignoring it.

=== Is Clean Code Only for Beginners?

Just like with the helmet, as we become seasoned developers we start trusting ourselves with the code.
First of all, we do tests. We also use architecture frameworks such as Spring, Angular or something third.
So, if we are testing, if we're using MVC, the rest is cosmetic, right?
In addition, we don't have all the time in the world to polish every corner of the application.
Experienced developers tend to underestimate clean code.

At least I speak about my personal perspective from the early days.
What changed for me is that I've joined a project that is in production for a loooong time.
We deal with uber classes, measured in thousands of lines of code.
Do you think that the class having several thousand lines is properly tested?
Do you think it does something important?
The only thing we can rely on is the messy code that we need to understand, day in, day out.
We're reaching near zero productivity. We're afraid of breaking things. We're stuck.

The point we reached is perfectly described in
https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882[Clean Code: A Handbook of Agile Software Craftsmanship].
There's something about the personal experience that makes you become a believer.
My second take on clean code book, was as reading the Agatha Christie's novel.

For the two years I'm practicing Clean Code routines in a much greater extent then ever before, I see a shift for the better.
This is what I'm trying to communicate.

=== Code Cleaning Spring PetClinic

Spring PetClinic is a good target as it is in a really good shape and familiar to millions.
In my belief, its the only demo application that has its own community.
In addition Spring as framework, just as clean code, is on a mission of enabling apps that are easy to change and evolve.

Following are the findings of Spring PetClinic review, sorted by the degree of drama:

include::01-single-responsibility-principle-violation.adoc[01 Single Responsibility Principle]

include::02-clean-code-tests.adoc[02 Testing]

include::03-Functions.adoc[03 Functions]

include::04-comments.adoc[04 Comments]

include::05-names.adoc[05 Names]

== Conclusion

What we learned by code cleaning Spring Petclinic is that coverage tool and high test coverage rate is not enough.
We must make sure that we test everything that can possible break, whatever that might be in practice.

Through our review of names, functions and comments we learned that its easy to gain many little wins, that are quick and safe to do,
and leave the code simpler, readable and easier to maintain.

There's no proper excuse of not learning clean code routines.
Being critical of the rules is understandable. Not taking the time to learn them, is simply irresponsible and lazy.
When it comes to practicing and applying the rules, for most of the time, the only thing needed, is to care enough and to do the changes.

[quote, Michael Fathers, 'Author of Working Effectively with Legacy Code']
____
Clean code always looks like it was written by someone who care
____
